---
- name: Install dependent packages of MySQL
  yum:
    name: "{{ packages }}"
    state: present
    lock_timeout: 180
  vars:
    packages:
      - MySQL-python
      - libselinux-python
      - yum-utils

- name: Install MySQL
  yum:
    name: mysql57-server
    skip_broken: yes
    lock_timeout: 180
  when: not ansible_check_mode

- name: Setting up automatic startup of mysql
  service:
    name: mysqld
    state: started
    enabled: yes

- name: Edit /root/.my.cnf
  template:
    src: roles/mysql/templates/my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: 0600

- name: Start MySQL service
  service:
    name: mysqld
    state: started
    enabled: yes
